"""empty message

Revision ID: 3237c76f3c07
Revises: 
Create Date: 2022-09-14 17:38:30.822398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3237c76f3c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('next_days_weather',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('min_temp', sa.JSON(), nullable=True),
    sa.Column('max_temp', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('today_weather',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=500), nullable=True),
    sa.Column('precip', sa.String(length=5), nullable=True),
    sa.Column('humidity', sa.String(length=5), nullable=True),
    sa.Column('wind', sa.JSON(), nullable=True),
    sa.Column('dayhour', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('today_weather')
    op.drop_table('next_days_weather')
    # ### end Alembic commands ###
